### ISSUE TITLE
Code no longer works with AM 7.3

### ISSUE THREAD

**Issue by echoloco** [ForgeRock/get-profile-property-auth-tree-node#7]
We deployed this node in 7.1.1 but when we upgraded to 7.3 it stopped working. The culprit:

```
Caused by: java.lang.NoSuchMethodError: 'com.sun.identity.idm.AMIdentity org.forgerock.openam.core.CoreWrapper.getIdentity(java.lang.String, java.lang.String)'
	at org.forgerock.openam.auth.nodes.GetProfilePropertyNode.process(GetProfilePropertyNode.java:89)
```

`CoreWrapper` does not seem to have a `getIdentity()` method anymore.
